import numpy as np
def get_primes(limit: int) -> list[int]: ...
def get_last_prime(limit: int) -> int: ...
def sum_primes(limit: int) -> int: ...
def sum_array(arr: list[int]) -> int: ...
def fft_convolve(signal:list[float], kernel:list[float]) ->list[float]: ...
def estimate_pi_rust(limit: int, threads: int) -> float: ...